### ISSUE TITLE
data processing problem

### ISSUE THREAD

**Issue by lz666win** [jocicmarko/ultrasound-nerve-segmentation#73]
I use python3.5.2,numpy is 1.14.3,here is traceback:

Traceback (most recent call last):
  File "C:/Users/lz666/PycharmProjects/ultrasound-nerve-segmentation/data.py", line 93, in <module>
    create_train_data()
  File "C:/Users/lz666/PycharmProjects/ultrasound-nerve-segmentation/data.py", line 37, in create_train_data
    imgs[i] = img
ValueError: setting an array element with a sequence.
in function create_train_data  ,imgs[i] = img is not work ,but in create_test_data,it is no problem,please help me about this problem

**Comment by lz666win** [comment]
I got result, when processing data, author use 'total = len(images)/2', then total is float.I changed as'total = int(len(images)/2)',there is no problem
