### ISSUE TITLE
Error, when I start data.py

### ISSUE THREAD

**Issue by SlimRG** [jocicmarko/ultrasound-nerve-segmentation#79]
`(base) C:\Users\BBCCA\Desktop\ultrasound-nerve-segmentation-master>python data.py

Traceback (most recent call last):
-File "data.py", line 92, in <module>
----create_train_data()
--File "data.py", line 19, in create_train_data
----imgs = np.ndarray((total, image_rows, image_cols), dtype=np.uint8)

TypeError: 'float' object cannot be interpreted as an integer`

I have Python 3.6.6 x64 (Anaconda For Windows)

**Comment by SlimRG** [comment]
Попробуйте заменить:

total = len(images) / 2
на (целочисленное деление):

total = len(images) // 2

**Comment by giemmecci** [comment]
This solved the issue for me:

`total = int(len(images) / 2)`

**Comment by SlimRG** [comment]
Difference?
